(()=>{"use strict";
const APP_VERSION="0.4", DB_NAME="mets-saha-db", DB_VERSION=1, STORE="kv", STATE_KEY="state", LEGACY_KEY="mets-saha-v01", MAX_PHOTOS=8;
let data={package:null,records:{}}, current=null, db=null, leafletMap=null, parcelLayer=null, userLayer=null, centroidLayer=null, watchId=null;
let neighborhoodMap=null, neighborhoodGroup=null, neighborhoodUserLayer=null, nearestLayer=null;
const $=s=>document.querySelector(s);
const toast=t=>{const e=$("#toast");e.textContent=t;e.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display="none",2600)};
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function dbGet(k){return new Promise((ok,no)=>{const t=db.transaction(STORE,"readonly"),r=t.objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function dbSet(k,v){return new Promise((ok,no)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(v,k);t.oncomplete=()=>ok();t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)})}
function dbClear(){return new Promise((ok,no)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).clear();t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
async function initStorage(){db=await openDb();const stored=await dbGet(STATE_KEY);if(stored&&typeof stored==="object")data=stored;else{try{const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||"null");if(legacy){data=legacy;await save();localStorage.removeItem(LEGACY_KEY);toast("v0.1 saha verileri v0.2 depolamasına taşındı.")}}catch{}}if(!data||typeof data!=="object")data={package:null,records:{}};data.records=data.records||{};try{if(navigator.storage?.persist)await navigator.storage.persist()}catch{} }
async function save(){data.meta={...(data.meta||{}),appVersion:APP_VERSION,savedAt:new Date().toISOString()};await dbSet(STATE_KEY,data);updateStorageInfo()}
function rec(p){return data.records[p.id]||(data.records[p.id]={propertyId:p.id,key:p.key,status:"draft",report:{...p.report},saha:{},photos:[],signature:""})}

function geometry(p){return (Array.isArray(p?.geometry)?p.geometry:[]).filter(x=>Array.isArray(x)&&Number.isFinite(Number(x[0]))&&Number.isFinite(Number(x[1]))).map(x=>[Number(x[0]),Number(x[1])])}
function centroid(points){if(!points.length)return null;let x=0,y=0;for(const p of points){x+=p[0];y+=p[1]}return[x/points.length,y/points.length]}
function pointInPolygon(lon,lat,points){if(points.length<3)return false;let inside=false;for(let i=0,j=points.length-1;i<points.length;j=i++){const xi=points[i][0],yi=points[i][1],xj=points[j][0],yj=points[j][1];const hit=((yi>lat)!=(yj>lat))&&(lon<(xj-xi)*(lat-yi)/((yj-yi)||1e-15)+xi);if(hit)inside=!inside}return inside}
function projectMeters(lon,lat,refLat){const r=6371000,k=Math.PI/180;return [r*lon*k*Math.cos(refLat*k),r*lat*k]}
function distanceToSegmentMeters(lon,lat,a,b){const ref=(lat+a[1]+b[1])/3,p=projectMeters(lon,lat,ref),p1=projectMeters(a[0],a[1],ref),p2=projectMeters(b[0],b[1],ref);const vx=p2[0]-p1[0],vy=p2[1]-p1[1],wx=p[0]-p1[0],wy=p[1]-p1[1],d=vx*vx+vy*vy;let t=d?(wx*vx+wy*vy)/d:0;t=Math.max(0,Math.min(1,t));return Math.hypot(p[0]-(p1[0]+t*vx),p[1]-(p1[1]+t*vy))}
function distanceToPolygonMeters(lon,lat,points){if(!points.length)return null;if(pointInPolygon(lon,lat,points))return 0;let m=Infinity;for(let i=0;i<points.length;i++)m=Math.min(m,distanceToSegmentMeters(lon,lat,points[i],points[(i+1)%points.length]));return Number.isFinite(m)?m:null}
function navigationUrl(p){const c=centroid(geometry(p));if(!c)return '';const lat=c[1].toFixed(7),lon=c[0].toFixed(7);return /iPhone|iPad|iPod/i.test(navigator.userAgent)?`https://maps.apple.com/?daddr=${lat},${lon}&dirflg=d`:`https://www.google.com/maps/dir/?api=1&destination=${lat},${lon}`}
function normText(v){return String(v??"").trim().toLocaleUpperCase("tr-TR")}
function uniqueSorted(a){return [...new Set(a.filter(Boolean))].sort((x,y)=>String(x).localeCompare(String(y),"tr-TR"))}
function lastGps(){const g=data.meta?.lastGps;return g&&Number.isFinite(Number(g.lat))&&Number.isFinite(Number(g.lon))?{lat:Number(g.lat),lon:Number(g.lon),accuracy:Number(g.accuracy)||0}:null}
function kmlNeedsReview(p){const st=normText(p?.kml?.status);return !!geometry(p).length && st && !["MATCHED","ESLESTI","EŞLEŞTİ"].includes(st)}
function propertyState(p){const r=rec(p);if(kmlNeedsReview(p))return "review";if(r.status==="completed")return "done";if(r.saha?.updatedAt||(r.photos||[]).length||r.signature)return "draft";return "todo"}
function stateLabel(p){const st=propertyState(p);return st==="done"?"Tamamlandı":st==="draft"?"Taslak":st==="review"?"KML kontrol":"Tespit edilmedi"}
function stateColor(p){const st=propertyState(p);return st==="done"?"#1c7c54":st==="draft"?"#d9981e":st==="review"?"#cc6c18":"#c43d3d"}
function setSelectOptions(el,vals,currentValue,placeholder){const keep=currentValue&&vals.includes(currentValue)?currentValue:(vals[0]||"");el.innerHTML=(placeholder?`<option value="">${esc(placeholder)}</option>`:"")+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join("");el.value=keep;return keep}
function syncNeighborhoodSelectors(){const props=data.package?.properties||[],dEl=$("#districtSelect"),mEl=$("#neighborhoodSelect");if(!dEl||!mEl)return;const oldD=dEl.value,oldM=mEl.value,ds=uniqueSorted(props.map(p=>p.ilce));const d=setSelectOptions(dEl,ds,oldD,"İlçe seçin");const ms=uniqueSorted(props.filter(p=>!d||p.ilce===d).map(p=>p.mahalle));setSelectOptions(mEl,ms,oldM,"Mahalle seçin")}
function selectedNeighborhoodProps(){const d=$("#districtSelect")?.value||"",m=$("#neighborhoodSelect")?.value||"";return (data.package?.properties||[]).filter(p=>(!d||p.ilce===d)&&(!m||p.mahalle===m))}
function neighborhoodStats(props){const withGeom=props.filter(p=>geometry(p).length),done=props.filter(p=>rec(p).status==="completed").length,draft=props.filter(p=>propertyState(p)==="draft").length,review=props.filter(p=>propertyState(p)==="review").length;return{total:props.length,withGeom:withGeom.length,missing:props.length-withGeom.length,done,draft,review,todo:Math.max(0,props.length-done-draft)}}
function popupHtml(p){return `<div class="neighborhood-popup"><b>${esc(p.ada||"—")} ada ${esc(p.parsel||"—")} parsel</b><small>${esc(p.mahalle||"")} · ${esc(p.yuzolcumu||"—")} m² · ${esc(p.cinsi||"—")}<br>${esc(stateLabel(p))}</small><button type="button" class="popup-open" data-open-neighborhood="${esc(p.id)}">Tespiti Aç</button></div>`}
function drawNeighborhoodFallback(props){const box=$("#neighborhoodFallback"),svg=$("#neighborhoodSvg"),withGeom=props.filter(p=>geometry(p).length);if(!withGeom.length){box.hidden=true;return}box.hidden=false;const gps=lastGps(),all=withGeom.flatMap(p=>geometry(p));if(gps)all.push([gps.lon,gps.lat]);const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=.06,dx=(maxX-minX)||.0001,dy=(maxY-minY)||.0001;const sx=x=>24+(x-(minX-dx*pad))/(dx*(1+2*pad))*672,sy=y=>446-(y-(minY-dy*pad))/(dy*(1+2*pad))*412;let html=`<rect x="1" y="1" width="718" height="478" rx="10" fill="#f7faf9" stroke="#cbd8d5"/>`;for(const p of withGeom){const pts=geometry(p),d=pts.map((q,i)=>`${i?'L':'M'} ${sx(q[0]).toFixed(1)} ${sy(q[1]).toFixed(1)}`).join(' ')+' Z',c=centroid(pts),col=stateColor(p);html+=`<path data-svg-open="${esc(p.id)}" d="${d}" fill="${col}33" stroke="${col}" stroke-width="2"/><text x="${sx(c[0]).toFixed(1)}" y="${sy(c[1]).toFixed(1)}" font-size="9" text-anchor="middle" fill="#17312d">${esc(p.ada||'')}/${esc(p.parsel||'')}</text>`}if(gps)html+=`<circle cx="${sx(gps.lon)}" cy="${sy(gps.lat)}" r="7" fill="#1769aa" stroke="white" stroke-width="3"/><text x="${sx(gps.lon)+10}" y="${sy(gps.lat)+4}" font-size="11" fill="#17312d">Siz</text>`;html+=`<text x="12" y="470" font-size="11" fill="#667772">Çevrimdışı mahalle krokisi · parsel üzerine dokunarak tespiti açabilirsiniz</text>`;svg.innerHTML=html;svg.querySelectorAll('[data-svg-open]').forEach(el=>el.addEventListener('click',()=>open(el.getAttribute('data-svg-open'))))}
function renderNeighborhoodMap(){const props=selectedNeighborhoodProps(),mapEl=$("#neighborhoodMap"),fallback=$("#neighborhoodFallback"),sum=$("#neighborhoodSummary"),count=$("#neighborhoodCount");if(!mapEl)return;const st=neighborhoodStats(props);count.textContent=`${st.total} taşınmaz`;sum.textContent=props.length?`${st.withGeom} KML'li · ${st.missing} KML yok · ${st.done} tamamlandı · ${st.draft} taslak${st.review?` · ${st.review} KML kontrol`:''}`:"Mahalle seçin.";const geomProps=props.filter(p=>geometry(p).length);if(!geomProps.length){mapEl.style.display="none";fallback.hidden=true;$("#nearestInfo").textContent=props.length?"Bu mahallede haritada gösterilebilecek KML geometrisi yok.":"";if(neighborhoodMap){neighborhoodMap.remove();neighborhoodMap=null}return}const gps=lastGps();if(window.L&&navigator.onLine){mapEl.style.display="block";fallback.hidden=true;try{if(neighborhoodMap){neighborhoodMap.remove();neighborhoodMap=null}neighborhoodMap=L.map(mapEl,{zoomControl:true,attributionControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap katkıda bulunanlar'}).addTo(neighborhoodMap);neighborhoodGroup=L.featureGroup().addTo(neighborhoodMap);for(const p of geomProps){const col=stateColor(p),layer=L.polygon(geometry(p).map(q=>[q[1],q[0]]),{color:col,weight:3,fillColor:col,fillOpacity:.20}).addTo(neighborhoodGroup);layer.bindPopup(popupHtml(p));const c=centroid(geometry(p));if(c)layer.bindTooltip(`${p.ada||'—'}/${p.parsel||'—'}`,{permanent:false,direction:'top',className:'mets-parcel-label'});}if(gps)neighborhoodUserLayer=L.marker([gps.lat,gps.lon],{icon:L.divIcon({className:'',html:'<div class="mets-neighborhood-user"></div>',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(neighborhoodMap).bindPopup(`Konumunuz · ±${Math.round(gps.accuracy||0)} m`);neighborhoodMap.fitBounds(neighborhoodGroup.getBounds(),{padding:[24,24],maxZoom:17});setTimeout(()=>neighborhoodMap.invalidateSize(),120)}catch(e){console.error(e);mapEl.style.display="none";drawNeighborhoodFallback(props)}}else{mapEl.style.display="none";drawNeighborhoodFallback(props)}}
function nearestIncomplete(gps){const props=selectedNeighborhoodProps().filter(p=>geometry(p).length&&rec(p).status!=="completed");let best=null;for(const p of props){const c=centroid(geometry(p));if(!c)continue;const d=distanceToPolygonMeters(gps.lon,gps.lat,geometry(p));if(d==null)continue;if(!best||d<best.distance)best={p,distance:d,c}}return best}
async function acquireNeighborhoodGps(showToast=true){if(!window.isSecureContext)throw Error("GPS için uygulamayı HTTPS üzerinden açın.");if(!navigator.geolocation)throw Error("Bu cihaz konum erişimini desteklemiyor.");return new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(async pos=>{data.meta={...(data.meta||{}),lastGps:{lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,at:new Date().toISOString()}};await save();renderNeighborhoodMap();if(showToast)toast("Konum mahalle haritasında gösterildi.");ok(data.meta.lastGps)},e=>no(Error("Konum alınamadı: "+e.message)),{enableHighAccuracy:true,timeout:20000,maximumAge:0}))}
async function showNearest(){try{const gps=lastGps()||await acquireNeighborhoodGps(false),best=nearestIncomplete(gps);if(!best)return toast("Bu mahallede KML'li ve tamamlanmamış parsel bulunamadı.");const d=best.distance<1000?`${Math.round(best.distance)} m`:`${(best.distance/1000).toFixed(2)} km`;$("#nearestInfo").innerHTML=`En yakın tamamlanmamış taşınmaz: <b>${esc(best.p.ada||'—')} ada ${esc(best.p.parsel||'—')} parsel</b> · yaklaşık ${d} <button type="button" class="popup-open" data-nearest-open="${esc(best.p.id)}">Tespiti Aç</button>`;$("#nearestInfo").querySelector('[data-nearest-open]').onclick=()=>open(best.p.id);if(neighborhoodMap){const target=[best.c[1],best.c[0]];neighborhoodMap.setView(target,Math.max(neighborhoodMap.getZoom(),18));if(nearestLayer)nearestLayer.remove();nearestLayer=L.marker(target,{icon:L.divIcon({className:'',html:'<div class="mets-nearest-ring"></div>',iconSize:[22,22],iconAnchor:[11,11]})}).addTo(neighborhoodMap);for(const lyr of neighborhoodGroup.getLayers()){try{const b=lyr.getBounds?.();if(b&&b.contains(target)){lyr.openPopup();break}}catch{}}}toast(`En yakın parsel yaklaşık ${d}.`)}catch(e){toast(e.message)}}

function userGps(){const g=current?rec(current).saha?.gps:null;return g&&Number.isFinite(Number(g.lat))&&Number.isFinite(Number(g.lon))?{lat:Number(g.lat),lon:Number(g.lon),accuracy:Number(g.accuracy)||0}:null}
function updateParcelStatus(){const pts=geometry(current),g=userGps(),el=$("#parcelStatus");if(!pts.length){el.textContent="Bu taşınmaz için güvenilir KML geometrisi yok.";el.className="parcel-status nogeom";return}if(!g){el.textContent="Parsel sınırı hazır. Konumunuzu almak için ‘Konumumu Güncelle’ye dokunun.";el.className="parcel-status muted";return}const inside=pointInPolygon(g.lon,g.lat,pts),dist=distanceToPolygonMeters(g.lon,g.lat,pts);el.className=`parcel-status ${inside?"inside":"outside"}`;el.textContent=inside?`✓ KML parsel sınırları içerisindesiniz · GPS hassasiyeti ±${Math.round(g.accuracy)} m`:`Parsel sınırına yaklaşık ${dist<1000?Math.round(dist)+" m":(dist/1000).toFixed(2)+" km"} uzaktasınız · GPS hassasiyeti ±${Math.round(g.accuracy)} m`}
function drawFallback(){const pts=geometry(current),svg=$("#parcelSvg"),box=$("#parcelFallback");if(!pts.length){box.hidden=true;return}box.hidden=false;const g=userGps(),all=[...pts];if(g){const c=centroid(pts),d=distanceToPolygonMeters(g.lon,g.lat,pts);if((d??0)<3000)all.push([g.lon,g.lat])}const xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys),pad=.12,dx=(maxX-minX)||.0001,dy=(maxY-minY)||.0001;const sx=x=>24+(x-(minX-dx*pad))/(dx*(1+2*pad))*312,sy=y=>236-(y-(minY-dy*pad))/(dy*(1+2*pad))*212;const d=pts.map((p,i)=>`${i?'L':'M'} ${sx(p[0]).toFixed(1)} ${sy(p[1]).toFixed(1)}`).join(' ')+' Z';let html=`<rect x="1" y="1" width="358" height="258" rx="10" fill="#f7faf9" stroke="#cbd8d5"/><path d="${d}" fill="rgba(31,79,70,.16)" stroke="#1f4f46" stroke-width="3"/>`;const c=centroid(pts);html+=`<circle cx="${sx(c[0])}" cy="${sy(c[1])}" r="5" fill="#a66710"/><text x="${sx(c[0])+8}" y="${sy(c[1])-7}" font-size="12" fill="#17312d">Parsel merkezi</text>`;if(g&&(distanceToPolygonMeters(g.lon,g.lat,pts)??0)<3000)html+=`<circle cx="${sx(g.lon)}" cy="${sy(g.lat)}" r="7" fill="#1769aa" stroke="white" stroke-width="3"/><text x="${sx(g.lon)+10}" y="${sy(g.lat)+4}" font-size="12" fill="#17312d">Siz</text>`;html+=`<text x="12" y="250" font-size="11" fill="#667772">Çevrimdışı kroki · kuzey yukarı · ölçek yalnız göreli konum içindir</text>`;svg.innerHTML=html}
function renderParcelMap(){const pts=geometry(current),mapEl=$("#parcelMap"),fallback=$("#parcelFallback"),nav=$("#navBtn");nav.disabled=!pts.length;updateParcelStatus();if(!pts.length){mapEl.style.display="none";fallback.hidden=true;return}const latlngs=pts.map(p=>[p[1],p[0]]),g=userGps(),c=centroid(pts);if(window.L&&navigator.onLine){mapEl.style.display="block";fallback.hidden=true;try{if(leafletMap){leafletMap.remove();leafletMap=null}leafletMap=L.map(mapEl,{zoomControl:true,attributionControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'© OpenStreetMap katkıda bulunanlar'}).addTo(leafletMap);parcelLayer=L.polygon(latlngs,{color:'#1f4f46',weight:4,fillColor:'#1f4f46',fillOpacity:.16}).addTo(leafletMap);leafletMap.fitBounds(parcelLayer.getBounds(),{padding:[28,28],maxZoom:19});centroidLayer=L.marker([c[1],c[0]],{icon:L.divIcon({className:'',html:'<div class="mets-centroid-dot"></div>',iconSize:[14,14],iconAnchor:[7,7]})}).addTo(leafletMap).bindPopup('Parsel merkezi');if(g)userLayer=L.marker([g.lat,g.lon],{icon:L.divIcon({className:'',html:'<div class="mets-user-dot"></div>',iconSize:[18,18],iconAnchor:[9,9]})}).addTo(leafletMap).bindPopup(`Konumunuz · ±${Math.round(g.accuracy)} m`);setTimeout(()=>leafletMap.invalidateSize(),120)}catch(e){console.error(e);mapEl.style.display="none";drawFallback()}}else{mapEl.style.display="none";drawFallback()}}

function render(){const pkg=data.package;$("#pkgInfo").textContent=pkg?`${pkg.properties.length} taşınmaz · Paket ${pkg.packageId}`:"Henüz saha paketi yüklenmedi.";syncNeighborhoodSelectors();const q=$("#search").value.toLocaleUpperCase("tr-TR"),st=$("#status").value;const arr=(pkg?.properties||[]).filter(p=>{const r=rec(p),txt=`${p.mahalle} ${p.ada} ${p.parsel} ${p.ilce}`.toLocaleUpperCase("tr-TR");return(!q||txt.includes(q))&&(st==="all"||r.status===st)});$("#list").innerHTML=arr.map(p=>{const r=rec(p);return`<button class="card item" data-id="${esc(p.id)}"><span><h3>${esc(p.mahalle||"—")} · ${esc(p.ada||"—")} ada ${esc(p.parsel||"—")} parsel</h3><small>${esc(p.ilce||"")} · ${esc(p.yuzolcumu||"—")} m² · ${esc(p.cinsi||"—")}</small></span><span class="chip ${r.status==="completed"?"done":""}">${r.status==="completed"?"Tamamlandı":"Taslak"}</span></button>`}).join("")||'<div class="card muted">Gösterilecek kayıt yok.</div>';document.querySelectorAll(".item").forEach(b=>b.onclick=()=>open(b.dataset.id));renderNeighborhoodMap();updateStorageInfo()}
async function loadPkg(file){const p=JSON.parse(await file.text());if(p.app!=="METS_SAHA_PAKETI"||!Array.isArray(p.properties))throw Error("Geçerli METS saha paketi değil.");const same=data.package?.packageId===p.packageId;if(!same&&data.package&&Object.values(data.records).some(r=>r.status==="completed"||r.saha?.updatedAt)){if(!confirm("Telefonda mevcut saha çalışması var. Yeni pakete geçmeden önce otomatik yedek indirilecek. Devam edilsin mi?"))return;downloadBackup("Otomatik_Oncesi");data={package:null,records:{}}}data.package=p;p.properties.forEach(x=>rec(x));await save();render();toast(`${p.properties.length} taşınmaz ${same?"güncellendi":"yüklendi"}.`)}
function open(id){const p=data.package?.properties?.find(x=>x.id===id);if(!p)return;current=p;const r=rec(p);$("#home").hidden=true;$("#editor").hidden=false;$("#identity").innerHTML=`<h2>${esc(p.mahalle)} · ${esc(p.ada)} ada ${esc(p.parsel)} parsel</h2><p>${esc(p.ilce)} · ${esc(p.yuzolcumu)} m² · ${esc(p.cinsi)}</p><small>Zemin/Taşınmaz No: ${esc(p.zeminId||p.tasinmazNo||"—")}</small>`;const f=$("#form"),rep=r.report||{};for(const el of f.elements){if(!el.name)continue;let v=rep[el.name];if(Array.isArray(v))v=v[0]||"";el.value=v||""}$("#gpsText").textContent=r.saha?.gps?`${r.saha.gps.lat.toFixed(6)}, ${r.saha.gps.lon.toFixed(6)} · ±${Math.round(r.saha.gps.accuracy||0)} m`:"Henüz alınmadı.";renderPhotos();drawSavedSignature();renderParcelMap()}
async function collect(){if(!current)return null;const r=rec(current),f=$("#form");for(const el of f.elements){if(!el.name)continue;if(el.name==="tespitSonucu"||el.name==="kullanimAmaclari")r.report[el.name]=el.value?[el.value]:[];else r.report[el.name]=el.value}r.saha={...(r.saha||{}),updatedAt:new Date().toISOString()};r.signature=$("#sig").dataset.value||r.signature||"";await save();return r}
function validate(r){const res=(r.report.tespitSonucu||[])[0],probs=[];if(!res)probs.push("Tespit sonucu");if((res==="İşgalli"||res==="Kısmen işgalli")&&!r.report.kullaniciAdi)probs.push("Kullanıcı/fuzuli şagil");if(res==="Kısmen işgalli"&&!r.report.kullanimAlani)probs.push("Kullanım alanı");if((res==="İşgalli"||res==="Kısmen işgalli")&&!(r.report.kullanimAmaclari||[])[0])probs.push("Kullanım amacı");return probs}
function resultPayload(){if(!data.package)return null;const results=Object.values(data.records).filter(r=>r.status==="completed"||r.saha?.updatedAt||r.saha?.gps||(r.photos||[]).length||r.signature).map(r=>({propertyId:r.propertyId,key:r.key,status:r.status,report:r.report,saha:r.saha,photos:r.photos,signature:r.signature}));return{app:"METS_SAHA_SONUCLARI",schemaVersion:2,packageId:data.package.packageId,exportedAt:new Date().toISOString(),pwaVersion:APP_VERSION,results}}
function downloadJson(obj,name){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportResults(){const out=resultPayload();if(!out)return toast("Önce saha paketi yükleyin.");downloadJson(out,`METS_Saha_Sonuclari_${new Date().toISOString().slice(0,10)}.json`);toast(`${out.results.length} kayıt dışa aktarıldı.`)}
function downloadBackup(prefix="METS_Saha_Cihaz_Yedegi"){downloadJson({app:"METS_SAHA_CIHAZ_YEDEGI",schemaVersion:1,exportedAt:new Date().toISOString(),state:data},`${prefix}_${new Date().toISOString().replace(/[:.]/g,"-").slice(0,19)}.json`)}
async function restoreBackup(file){const x=JSON.parse(await file.text());if(x.app!=="METS_SAHA_CIHAZ_YEDEGI"||!x.state?.records)throw Error("Geçerli METS Saha cihaz yedeği değil.");if(data.package&&!confirm("Mevcut cihaz verisinin üzerine yedek geri yüklenecek. Devam edilsin mi?"))return;data=x.state;await save();current=null;$("#editor").hidden=true;$("#home").hidden=false;render();toast("Cihaz yedeği geri yüklendi.")}
function renderPhotos(){const r=rec(current);$("#photos").innerHTML=(r.photos||[]).map((src,i)=>`<div><img src="${src}"><button type="button" data-rm="${i}" class="ghost">Sil</button></div>`).join("");document.querySelectorAll("[data-rm]").forEach(b=>b.onclick=async()=>{r.photos.splice(+b.dataset.rm,1);await save();renderPhotos()})}
function compress(file){return new Promise((ok,no)=>{const img=new Image,fr=new FileReader;fr.onload=()=>{img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);ok(c.toDataURL("image/jpeg",.7))};img.onerror=no;img.src=fr.result};fr.onerror=no;fr.readAsDataURL(file)})}
async function updateStorageInfo(){try{if(!navigator.storage?.estimate)return;const e=await navigator.storage.estimate(),mb=n=>((n||0)/1048576).toFixed(1);$("#storageInfo").textContent=`Cihaz depolaması: yaklaşık ${mb(e.usage)} MB kullanılıyor${e.quota?` / ${mb(e.quota)} MB kullanılabilir kota`:""}.`;}catch{}}
function updateNet(){const online=navigator.onLine;$("#netBadge").textContent=online?"Çevrimiçi":"Çevrimdışı";$("#netBadge").className=`net ${online?"on":"off"}`}
const canvas=$("#sig"),ctx=canvas.getContext("2d");ctx.lineWidth=4;ctx.lineCap="round";let drawing=false;function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}function start(e){drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function move(e){if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function end(){if(!drawing)return;drawing=false;canvas.dataset.value=canvas.toDataURL("image/png")}function drawSavedSignature(){ctx.clearRect(0,0,canvas.width,canvas.height);const r=rec(current),src=r.signature||"";canvas.dataset.value=src;if(src){const im=new Image;im.onload=()=>ctx.drawImage(im,0,0,canvas.width,canvas.height);im.src=src}}
canvas.addEventListener("pointerdown",start);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",end);canvas.addEventListener("pointerleave",end);
$("#clearSig").onclick=async()=>{ctx.clearRect(0,0,canvas.width,canvas.height);canvas.dataset.value="";if(current){rec(current).signature="";await save()}};
$("#packageInput").onchange=async e=>{try{if(e.target.files[0])await loadPkg(e.target.files[0])}catch(x){toast(x.message)}e.target.value=""};
$("#backupInput").onchange=async e=>{try{if(e.target.files[0])await restoreBackup(e.target.files[0])}catch(x){toast(x.message)}e.target.value=""};
$("#exportBtn").onclick=exportResults;$("#backupBtn").onclick=()=>downloadBackup();$("#search").oninput=render;$("#status").onchange=render;
$("#districtSelect").onchange=()=>{const props=data.package?.properties||[],d=$("#districtSelect").value,ms=uniqueSorted(props.filter(p=>!d||p.ilce===d).map(p=>p.mahalle));setSelectOptions($("#neighborhoodSelect"),ms,"","Mahalle seçin");$("#nearestInfo").textContent="";renderNeighborhoodMap()};
$("#neighborhoodSelect").onchange=()=>{$("#nearestInfo").textContent="";renderNeighborhoodMap()};
$("#neighborhoodGpsBtn").onclick=()=>acquireNeighborhoodGps().catch(e=>toast(e.message));
$("#nearestBtn").onclick=showNearest;
$("#neighborhoodMap").addEventListener("click",e=>{const b=e.target.closest?.("[data-open-neighborhood]");if(b)open(b.getAttribute("data-open-neighborhood"))});
$("#back").onclick=async()=>{if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;$("#trackBtn").textContent="Canlı Takip Başlat"}await collect();$("#editor").hidden=true;$("#home").hidden=false;render()};
$("#saveDraft").onclick=async()=>{const r=await collect();r.status="draft";await save();toast("Taslak kaydedildi.")};
$("#complete").onclick=async()=>{const r=await collect(),p=validate(r);if(p.length&&!confirm(`Eksik alanlar: ${p.join(", ")}. Yine de tamamlandı işaretlensin mi?`))return;r.status="completed";r.saha={...(r.saha||{}),completedAt:new Date().toISOString()};await save();toast("Tespit tamamlandı.");setTimeout(()=>$("#back").click(),450)};
async function acceptGpsPosition(p,live=false){if(!current)return;const r=rec(current),gps={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,altitude:p.coords.altitude,heading:p.coords.heading,speed:p.coords.speed,at:new Date().toISOString()};r.saha={...(r.saha||{}),gps};data.meta={...(data.meta||{}),lastGps:{lat:gps.lat,lon:gps.lon,accuracy:gps.accuracy,at:gps.at}};await save();$("#gpsText").textContent=`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)} · ±${Math.round(p.coords.accuracy)} m${live?" · canlı":""}`;renderParcelMap()}
$("#gpsBtn").onclick=()=>{if(!window.isSecureContext)return toast("GPS için uygulamayı HTTPS üzerinden açın.");if(!navigator.geolocation)return toast("Bu cihaz konum erişimini desteklemiyor.");$("#gpsText").textContent="Konum alınıyor…";navigator.geolocation.getCurrentPosition(async p=>{await acceptGpsPosition(p,false);toast("Konum kaydedildi ve parsel mesafesi hesaplandı.")},e=>{toast("Konum alınamadı: "+e.message);$("#gpsText").textContent="Konum alınamadı."},{enableHighAccuracy:true,timeout:20000,maximumAge:0})};
$("#trackBtn").onclick=()=>{if(!window.isSecureContext)return toast("Canlı GPS için uygulamayı HTTPS üzerinden açın.");if(!navigator.geolocation)return toast("Bu cihaz konum erişimini desteklemiyor.");if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;$("#trackBtn").textContent="Canlı Takip Başlat";toast("Canlı takip durduruldu.");return}$("#trackBtn").textContent="Canlı Takibi Durdur";watchId=navigator.geolocation.watchPosition(p=>acceptGpsPosition(p,true).catch(console.error),e=>toast("Canlı konum alınamadı: "+e.message),{enableHighAccuracy:true,timeout:20000,maximumAge:2000});toast("Canlı parsel takibi başladı.")};
$("#navBtn").onclick=()=>{if(!current)return;const u=navigationUrl(current);if(!u)return toast("Bu taşınmazda navigasyon için KML geometrisi yok.");window.open(u,"_blank","noopener")};
$("#photoInput").onchange=async e=>{const r=rec(current);for(const f of [...e.target.files]){if(r.photos.length>=MAX_PHOTOS)break;try{r.photos.push(await compress(f))}catch{}}try{await save()}catch(err){toast("Fotoğraf kaydedilemedi. Cihaz depolamasını/yedeği kontrol edin.");console.error(err)}renderPhotos();e.target.value="";toast(`${r.photos.length} fotoğraf kaydedildi.`)};
$("#resetBtn").onclick=async()=>{if(!confirm("Cihazdaki tüm METS Saha paketleri, tespitler, fotoğraflar ve imzalar silinecek. Önce yedek aldığınızdan emin misiniz?"))return;if(!confirm("Bu işlem geri alınamaz. Veriler gerçekten temizlensin mi?"))return;await dbClear();data={package:null,records:{}};current=null;render();toast("Cihaz verileri temizlendi.")};
$("#installHelp").onclick=()=>$("#help").showModal();$("#closeHelp").onclick=()=>$("#help").close();window.addEventListener("online",()=>{updateNet();if(current)renderParcelMap();renderNeighborhoodMap()});window.addEventListener("offline",()=>{updateNet();if(current)renderParcelMap();renderNeighborhoodMap()});
async function boot(){try{await initStorage();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});updateNet();render()}catch(e){console.error(e);toast("Yerel depolama başlatılamadı: "+e.message)}}boot();
})();
