(()=>{"use strict";
const APP_VERSION="0.2", DB_NAME="mets-saha-db", DB_VERSION=1, STORE="kv", STATE_KEY="state", LEGACY_KEY="mets-saha-v01", MAX_PHOTOS=8;
let data={package:null,records:{}}, current=null, db=null;
const $=s=>document.querySelector(s);
const toast=t=>{const e=$("#toast");e.textContent=t;e.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display="none",2600)};
const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
function openDb(){return new Promise((ok,no)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function dbGet(k){return new Promise((ok,no)=>{const t=db.transaction(STORE,"readonly"),r=t.objectStore(STORE).get(k);r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
function dbSet(k,v){return new Promise((ok,no)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).put(v,k);t.oncomplete=()=>ok();t.onerror=()=>no(t.error);t.onabort=()=>no(t.error)})}
function dbClear(){return new Promise((ok,no)=>{const t=db.transaction(STORE,"readwrite");t.objectStore(STORE).clear();t.oncomplete=()=>ok();t.onerror=()=>no(t.error)})}
async function initStorage(){db=await openDb();const stored=await dbGet(STATE_KEY);if(stored&&typeof stored==="object")data=stored;else{try{const legacy=JSON.parse(localStorage.getItem(LEGACY_KEY)||"null");if(legacy){data=legacy;await save();localStorage.removeItem(LEGACY_KEY);toast("v0.1 saha verileri v0.2 depolamasına taşındı.")}}catch{}}if(!data||typeof data!=="object")data={package:null,records:{}};data.records=data.records||{};try{if(navigator.storage?.persist)await navigator.storage.persist()}catch{} }
async function save(){data.meta={...(data.meta||{}),appVersion:APP_VERSION,savedAt:new Date().toISOString()};await dbSet(STATE_KEY,data);updateStorageInfo()}
function rec(p){return data.records[p.id]||(data.records[p.id]={propertyId:p.id,key:p.key,status:"draft",report:{...p.report},saha:{},photos:[],signature:""})}
function render(){const pkg=data.package;$("#pkgInfo").textContent=pkg?`${pkg.properties.length} taşınmaz · Paket ${pkg.packageId}`:"Henüz saha paketi yüklenmedi.";const q=$("#search").value.toLocaleUpperCase("tr-TR"),st=$("#status").value;const arr=(pkg?.properties||[]).filter(p=>{const r=rec(p),txt=`${p.mahalle} ${p.ada} ${p.parsel} ${p.ilce}`.toLocaleUpperCase("tr-TR");return(!q||txt.includes(q))&&(st==="all"||r.status===st)});$("#list").innerHTML=arr.map(p=>{const r=rec(p);return`<button class="card item" data-id="${esc(p.id)}"><span><h3>${esc(p.mahalle||"—")} · ${esc(p.ada||"—")} ada ${esc(p.parsel||"—")} parsel</h3><small>${esc(p.ilce||"")} · ${esc(p.yuzolcumu||"—")} m² · ${esc(p.cinsi||"—")}</small></span><span class="chip ${r.status==="completed"?"done":""}">${r.status==="completed"?"Tamamlandı":"Taslak"}</span></button>`}).join("")||'<div class="card muted">Gösterilecek kayıt yok.</div>';document.querySelectorAll(".item").forEach(b=>b.onclick=()=>open(b.dataset.id));updateStorageInfo()}
async function loadPkg(file){const p=JSON.parse(await file.text());if(p.app!=="METS_SAHA_PAKETI"||!Array.isArray(p.properties))throw Error("Geçerli METS saha paketi değil.");const same=data.package?.packageId===p.packageId;if(!same&&data.package&&Object.values(data.records).some(r=>r.status==="completed"||r.saha?.updatedAt)){if(!confirm("Telefonda mevcut saha çalışması var. Yeni pakete geçmeden önce otomatik yedek indirilecek. Devam edilsin mi?"))return;downloadBackup("Otomatik_Oncesi");data={package:null,records:{}}}data.package=p;p.properties.forEach(x=>rec(x));await save();render();toast(`${p.properties.length} taşınmaz ${same?"güncellendi":"yüklendi"}.`)}
function open(id){const p=data.package?.properties?.find(x=>x.id===id);if(!p)return;current=p;const r=rec(p);$("#home").hidden=true;$("#editor").hidden=false;$("#identity").innerHTML=`<h2>${esc(p.mahalle)} · ${esc(p.ada)} ada ${esc(p.parsel)} parsel</h2><p>${esc(p.ilce)} · ${esc(p.yuzolcumu)} m² · ${esc(p.cinsi)}</p><small>Zemin/Taşınmaz No: ${esc(p.zeminId||p.tasinmazNo||"—")}</small>`;const f=$("#form"),rep=r.report||{};for(const el of f.elements){if(!el.name)continue;let v=rep[el.name];if(Array.isArray(v))v=v[0]||"";el.value=v||""}$("#gpsText").textContent=r.saha?.gps?`${r.saha.gps.lat.toFixed(6)}, ${r.saha.gps.lon.toFixed(6)} · ±${Math.round(r.saha.gps.accuracy||0)} m`:"Henüz alınmadı.";renderPhotos();drawSavedSignature()}
async function collect(){if(!current)return null;const r=rec(current),f=$("#form");for(const el of f.elements){if(!el.name)continue;if(el.name==="tespitSonucu"||el.name==="kullanimAmaclari")r.report[el.name]=el.value?[el.value]:[];else r.report[el.name]=el.value}r.saha={...(r.saha||{}),updatedAt:new Date().toISOString()};r.signature=$("#sig").dataset.value||r.signature||"";await save();return r}
function validate(r){const res=(r.report.tespitSonucu||[])[0],probs=[];if(!res)probs.push("Tespit sonucu");if((res==="İşgalli"||res==="Kısmen işgalli")&&!r.report.kullaniciAdi)probs.push("Kullanıcı/fuzuli şagil");if(res==="Kısmen işgalli"&&!r.report.kullanimAlani)probs.push("Kullanım alanı");if((res==="İşgalli"||res==="Kısmen işgalli")&&!(r.report.kullanimAmaclari||[])[0])probs.push("Kullanım amacı");return probs}
function resultPayload(){if(!data.package)return null;const results=Object.values(data.records).filter(r=>r.status==="completed"||r.saha?.updatedAt||r.saha?.gps||(r.photos||[]).length||r.signature).map(r=>({propertyId:r.propertyId,key:r.key,status:r.status,report:r.report,saha:r.saha,photos:r.photos,signature:r.signature}));return{app:"METS_SAHA_SONUCLARI",schemaVersion:2,packageId:data.package.packageId,exportedAt:new Date().toISOString(),pwaVersion:APP_VERSION,results}}
function downloadJson(obj,name){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([JSON.stringify(obj,null,2)],{type:"application/json"}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function exportResults(){const out=resultPayload();if(!out)return toast("Önce saha paketi yükleyin.");downloadJson(out,`METS_Saha_Sonuclari_${new Date().toISOString().slice(0,10)}.json`);toast(`${out.results.length} kayıt dışa aktarıldı.`)}
function downloadBackup(prefix="METS_Saha_Cihaz_Yedegi"){downloadJson({app:"METS_SAHA_CIHAZ_YEDEGI",schemaVersion:1,exportedAt:new Date().toISOString(),state:data},`${prefix}_${new Date().toISOString().replace(/[:.]/g,"-").slice(0,19)}.json`)}
async function restoreBackup(file){const x=JSON.parse(await file.text());if(x.app!=="METS_SAHA_CIHAZ_YEDEGI"||!x.state?.records)throw Error("Geçerli METS Saha cihaz yedeği değil.");if(data.package&&!confirm("Mevcut cihaz verisinin üzerine yedek geri yüklenecek. Devam edilsin mi?"))return;data=x.state;await save();current=null;$("#editor").hidden=true;$("#home").hidden=false;render();toast("Cihaz yedeği geri yüklendi.")}
function renderPhotos(){const r=rec(current);$("#photos").innerHTML=(r.photos||[]).map((src,i)=>`<div><img src="${src}"><button type="button" data-rm="${i}" class="ghost">Sil</button></div>`).join("");document.querySelectorAll("[data-rm]").forEach(b=>b.onclick=async()=>{r.photos.splice(+b.dataset.rm,1);await save();renderPhotos()})}
function compress(file){return new Promise((ok,no)=>{const img=new Image,fr=new FileReader;fr.onload=()=>{img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement("canvas");c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext("2d").drawImage(img,0,0,c.width,c.height);ok(c.toDataURL("image/jpeg",.7))};img.onerror=no;img.src=fr.result};fr.onerror=no;fr.readAsDataURL(file)})}
async function updateStorageInfo(){try{if(!navigator.storage?.estimate)return;const e=await navigator.storage.estimate(),mb=n=>((n||0)/1048576).toFixed(1);$("#storageInfo").textContent=`Cihaz depolaması: yaklaşık ${mb(e.usage)} MB kullanılıyor${e.quota?` / ${mb(e.quota)} MB kullanılabilir kota`:""}.`;}catch{}}
function updateNet(){const online=navigator.onLine;$("#netBadge").textContent=online?"Çevrimiçi":"Çevrimdışı";$("#netBadge").className=`net ${online?"on":"off"}`}
const canvas=$("#sig"),ctx=canvas.getContext("2d");ctx.lineWidth=4;ctx.lineCap="round";let drawing=false;function pos(e){const r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height}}function start(e){drawing=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault()}function move(e){if(!drawing)return;const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault()}function end(){if(!drawing)return;drawing=false;canvas.dataset.value=canvas.toDataURL("image/png")}function drawSavedSignature(){ctx.clearRect(0,0,canvas.width,canvas.height);const r=rec(current),src=r.signature||"";canvas.dataset.value=src;if(src){const im=new Image;im.onload=()=>ctx.drawImage(im,0,0,canvas.width,canvas.height);im.src=src}}
canvas.addEventListener("pointerdown",start);canvas.addEventListener("pointermove",move);canvas.addEventListener("pointerup",end);canvas.addEventListener("pointerleave",end);
$("#clearSig").onclick=async()=>{ctx.clearRect(0,0,canvas.width,canvas.height);canvas.dataset.value="";if(current){rec(current).signature="";await save()}};
$("#packageInput").onchange=async e=>{try{if(e.target.files[0])await loadPkg(e.target.files[0])}catch(x){toast(x.message)}e.target.value=""};
$("#backupInput").onchange=async e=>{try{if(e.target.files[0])await restoreBackup(e.target.files[0])}catch(x){toast(x.message)}e.target.value=""};
$("#exportBtn").onclick=exportResults;$("#backupBtn").onclick=()=>downloadBackup();$("#search").oninput=render;$("#status").onchange=render;
$("#back").onclick=async()=>{await collect();$("#editor").hidden=true;$("#home").hidden=false;render()};
$("#saveDraft").onclick=async()=>{const r=await collect();r.status="draft";await save();toast("Taslak kaydedildi.")};
$("#complete").onclick=async()=>{const r=await collect(),p=validate(r);if(p.length&&!confirm(`Eksik alanlar: ${p.join(", ")}. Yine de tamamlandı işaretlensin mi?`))return;r.status="completed";r.saha={...(r.saha||{}),completedAt:new Date().toISOString()};await save();toast("Tespit tamamlandı.");setTimeout(()=>$("#back").click(),450)};
$("#gpsBtn").onclick=()=>{if(!window.isSecureContext)return toast("GPS için uygulamayı HTTPS üzerinden açın.");if(!navigator.geolocation)return toast("Bu cihaz konum erişimini desteklemiyor.");$("#gpsText").textContent="Konum alınıyor…";navigator.geolocation.getCurrentPosition(async p=>{const r=rec(current);r.saha={...(r.saha||{}),gps:{lat:p.coords.latitude,lon:p.coords.longitude,accuracy:p.coords.accuracy,altitude:p.coords.altitude,at:new Date().toISOString()}};await save();$("#gpsText").textContent=`${p.coords.latitude.toFixed(6)}, ${p.coords.longitude.toFixed(6)} · ±${Math.round(p.coords.accuracy)} m`;toast("Konum kaydedildi.")},e=>{toast("Konum alınamadı: "+e.message);$("#gpsText").textContent="Konum alınamadı."},{enableHighAccuracy:true,timeout:20000,maximumAge:0})};
$("#photoInput").onchange=async e=>{const r=rec(current);for(const f of [...e.target.files]){if(r.photos.length>=MAX_PHOTOS)break;try{r.photos.push(await compress(f))}catch{}}try{await save()}catch(err){toast("Fotoğraf kaydedilemedi. Cihaz depolamasını/yedeği kontrol edin.");console.error(err)}renderPhotos();e.target.value="";toast(`${r.photos.length} fotoğraf kaydedildi.`)};
$("#resetBtn").onclick=async()=>{if(!confirm("Cihazdaki tüm METS Saha paketleri, tespitler, fotoğraflar ve imzalar silinecek. Önce yedek aldığınızdan emin misiniz?"))return;if(!confirm("Bu işlem geri alınamaz. Veriler gerçekten temizlensin mi?"))return;await dbClear();data={package:null,records:{}};current=null;render();toast("Cihaz verileri temizlendi.")};
$("#installHelp").onclick=()=>$("#help").showModal();$("#closeHelp").onclick=()=>$("#help").close();window.addEventListener("online",updateNet);window.addEventListener("offline",updateNet);
async function boot(){try{await initStorage();if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});updateNet();render()}catch(e){console.error(e);toast("Yerel depolama başlatılamadı: "+e.message)}}boot();
})();
